name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Side by Side testing sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build CsharpFunctionDumper.sln
      - name: Compress
        run: Compress-Archive CsharpFunctionDumper/bin/Debug/netcoreapp3.1/* CSharpFunctionDumper.zip
        shell: powershell
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "CSharpFunctionDumper"
          files: |
            CSharpFunctionDumper.zip